#!/bin/sh -e

CP_USERNAME=pirat
CP_HOSTNAME=codingpirates

lb config noauto \
          --apt apt \
          --apt-indices true \
          --apt-recommends true \
          --architectures amd64 \
          --binary-images iso-hybrid \
          --binary-filesystem fat32 \
          --bootappend-live "boot=live components autologin quiet noeject username=${CP_USERNAME} hostname=${CP_HOSTNAME} locales=da_DK.UTF-8 keyboard-layouts=dk" \
          --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl,gpg,gnupg2,software-properties-common,curl" \
          --cache true \
          --checksums none \
          --compression none \
          --debian-installer live \
          --debian-installer-gui false \
          --debug \
          --distribution bullseye \
          --iso-application "CodingPiratesOS Live" \
          --iso-preparer "magnus@darkmagus.dk" \
          --iso-publisher "magnus@darkmagus.dk" \
          --iso-volume "CodingPiratesOS-live-amd64" \
          --linux-packages "linux-image linux-headers" \
          --memtest none \
          --mirror-bootstrap http://ftp.dk.debian.org/debian/ \
          --mirror-binary http://ftp.dk.debian.org/debian/ \
          --mode debian \
          --security true \
          --win32-loader true \
          --archive-areas "main contrib non-free" \
          --firmware-chroot true \
          ${@}

#nouveau.modeset=0
