#!/bin/sh -e

lb config noauto \
          --apt apt \
          --apt-indices true \
          --apt-recommends true \
          --apt-source-archives false \
          --architectures amd64 \
          --binary-images iso-hybrid \
          --binary-filesystem fat32 \
          --bootappend-live "boot=live components autologin noeject" \
          --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl,gpg,gnupg2,software-properties-common,curl" \
          --cache true \
          --checksums none \
          --compression none \
          --color \
          --debian-installer none \
          --distribution bullseye \
          --iso-application "CodingPiratesOS Live" \
          --iso-preparer "magnus@darkmagus.dk" \
          --iso-publisher "magnus@darkmagus.dk" \
          --iso-volume "CodingPiratesOS-live-amd64" \
          --linux-packages "linux-image linux-headers" \
          --memtest none \
          --mirror-bootstrap http://mirror.one.com/debian/ \
          --mirror-binary http://mirror.one.com/debian/ \
          --mode debian \
          --security true \
          --win32-loader true \
          --archive-areas "main contrib non-free" \
          --firmware-chroot true \
          ${@}

#nouveau.modeset=0
